INSERT INTO paises (nombre, dominio) VALUES
  ("Afganistán","AF"),
  ("Albania","AL"),
  ("Alemania","DE"),
  ("Andorra","AD"),
  ("Angola","AO"),
  ("Anguila","AI"),
  ("Antártida","AQ"),
  ("Antigua y Barbuda","AG"),
  ("Arabia Saudita","SA"),
  ("Argelia","DZ"),
  ("Argentina","AR"),
  ("Armenia","AM"),
  ("Aruba","AW"),
  ("Australia","AU"),
  ("Austria","AT"),
  ("Azerbaiyán","AZ"),
  ("Bélgica","BE"),
  ("Bahamas","BS"),
  ("Bahrein","BH"),
  ("Bangladesh","BD"),
  ("Barbados","BB"),
  ("Belice","BZ"),
  ("Benín","BJ"),
  ("Bhután","BT"),
  ("Bielorrusia","BY"),
  ("Birmania","MM"),
  ("Bolivia","BO"),
  ("Bosnia y Herzegovina","BA"),
  ("Botsuana","BW"),
  ("Brasil","BR"),
  ("Brunéi","BN"),
  ("Bulgaria","BG"),
  ("Burkina Faso","BF"),
  ("Burundi","BI"),
  ("Cabo Verde","CV"),
  ("Camboya","KH"),
  ("Camerún","CM"),
  ("Canadá","CA"),
  ("Chad","TD"),
  ("Chile","CL"),
  ("China","CN"),
  ("Chipre","CY"),
  ("Ciudad del Vaticano","VA"),
  ("Colombia","CO"),
  ("Comoras","KM"),
  ("República del Congo","CG"),
  ("República Democrática del Congo","CD"),
  ("Corea del Norte","KP"),
  ("Corea del Sur","KR"),
  ("Costa de Marfil","CI"),
  ("Costa Rica","CR"),
  ("Croacia","HR"),
  ("Cuba","CU"),
  ("Curazao","CW"),
  ("Dinamarca","DK"),
  ("Dominica","DM"),
  ("Ecuador","EC"),
  ("Egipto","EG"),
  ("El Salvador","SV"),
  ("Emiratos Árabes Unidos","AE"),
  ("Eritrea","ER"),
  ("Eslovaquia","SK"),
  ("Eslovenia","SI"),
  ("España","ES"),
  ("Estados Unidos de América","US"),
  ("Estonia","EE"),
  ("Etiopía","ET"),
  ("Filipinas","PH"),
  ("Finlandia","FI"),
  ("Fiyi","FJ"),
  ("Francia","FR"),
  ("Gabón","GA"),
  ("Gambia","GM"),
  ("Georgia","GE"),
  ("Ghana","GH"),
  ("Gibraltar","GI"),
  ("Granada","GD"),
  ("Grecia","GR"),
  ("Groenlandia","GL"),
  ("Guadalupe","GP"),
  ("Guam","GU"),
  ("Guatemala","GT"),
  ("Guayana Francesa","GF"),
  ("Guernsey","GG"),
  ("Guinea","GN"),
  ("Guinea Ecuatorial","GQ"),
  ("Guinea-Bissau","GW"),
  ("Guyana","GY"),
  ("Haití","HT"),
  ("Honduras","HN"),
  ("Hong kong","HK"),
  ("Hungría","HU"),
  ("India","IN"),
  ("Indonesia","ID"),
  ("Irán","IR"),
  ("Irak","IQ"),
  ("Irlanda","IE"),
  ("Isla Bouvet","BV"),
  ("Isla de Man","IM"),
  ("Isla de Navidad","CX"),
  ("Isla Norfolk","NF"),
  ("Islandia","IS"),
  ("Islas Bermudas","BM"),
  ("Islas Caimán","KY"),
  ("Islas Cocos (Keeling)","CC"),
  ("Islas Cook","CK"),
  ("Islas de Åland","AX"),
  ("Islas Feroe","FO"),
  ("Islas Georgias del Sur y Sandwich del Sur","GS"),
  ("Islas Heard y McDonald","HM"),
  ("Islas Maldivas","MV"),
  ("Islas Malvinas","FK"),
  ("Islas Marianas del Norte","MP"),
  ("Islas Marshall","MH"),
  ("Islas Pitcairn","PN"),
  ("Islas Salomón","SB"),
  ("Islas Turcas y Caicos","TC"),
  ("Islas Ultramarinas Menores de Estados Unidos","UM"),
  ("Islas Vírgenes Británicas","VG"),
  ("Islas Vírgenes de los Estados Unidos","VI"),
  ("Israel","IL"),
  ("Italia","IT"),
  ("Jamaica","JM"),
  ("Japón","JP"),
  ("Jersey","JE"),
  ("Jordania","JO"),
  ("Kazajistán","KZ"),
  ("Kenia","KE"),
  ("Kirguistán","KG"),
  ("Kiribati","KI"),
  ("Kuwait","KW"),
  ("Líbano","LB"),
  ("Laos","LA"),
  ("Lesoto","LS"),
  ("Letonia","LV"),
  ("Liberia","LR"),
  ("Libia","LY"),
  ("Liechtenstein","LI"),
  ("Lituania","LT"),
  ("Luxemburgo","LU"),
  ("México","MX"),
  ("Mónaco","MC"),
  ("Macao","MO"),
  ("Macedônia","MK"),
  ("Madagascar","MG"),
  ("Malasia","MY"),
  ("Malawi","MW"),
  ("Mali","ML"),
  ("Malta","MT"),
  ("Marruecos","MA"),
  ("Martinica","MQ"),
  ("Mauricio","MU"),
  ("Mauritania","MR"),
  ("Mayotte","YT"),
  ("Micronesia","FM"),
  ("Moldavia","MD"),
  ("Mongolia","MN"),
  ("Montenegro","ME"),
  ("Montserrat","MS"),
  ("Mozambique","MZ"),
  ("Namibia","NA"),
  ("Nauru","NR"),
  ("Nepal","NP"),
  ("Nicaragua","NI"),
  ("Niger","NE"),
  ("Nigeria","NG"),
  ("Niue","NU"),
  ("Noruega","NO"),
  ("Nueva Caledonia","NC"),
  ("Nueva Zelanda","NZ"),
  ("Omán","OM"),
  ("Países Bajos","NL"),
  ("Pakistán","PK"),
  ("Palau","PW"),
  ("Palestina","PS"),
  ("Panamá","PA"),
  ("Papúa Nueva Guinea","PG"),
  ("Paraguay","PY"),
  ("Perú","PE"),
  ("Polinesia Francesa","PF"),
  ("Polonia","PL"),
  ("Portugal","PT"),
  ("Puerto Rico","PR"),
  ("Qatar","QA"),
  ("Reino Unido","GB"),
  ("República Centroafricana","CF"),
  ("República Checa","CZ"),
  ("República Dominicana","DO"),
  ("República de Sudán del Sur","SS"),
  ("Reunión","RE"),
  ("Ruanda","RW"),
  ("Rumanía","RO"),
  ("Rusia","RU"),
  ("Sahara Occidental","EH"),
  ("Samoa","WS"),
  ("Samoa Americana","AS"),
  ("San Bartolomé","BL"),
  ("San Cristóbal y Nieves","KN"),
  ("San Marino","SM"),
  ("San Martín (Francia)","MF"),
  ("San Pedro y Miquelón","PM"),
  ("San Vicente y las Granadinas","VC"),
  ("Santa Elena","SH"),
  ("Santa Lucía","LC"),
  ("Santo Tomé y Príncipe","ST"),
  ("Senegal","SN"),
  ("Serbia","RS"),
  ("Seychelles","SC"),
  ("Sierra Leona","SL"),
  ("Singapur","SG"),
  ("Sint Maarten","SX"),
  ("Siria","SY"),
  ("Somalia","SO"),
  ("Sri lanka","LK"),
  ("Sudáfrica","ZA"),
  ("Sudán","SD"),
  ("Suecia","SE"),
  ("Suiza","CH"),
  ("Surinám","SR"),
  ("Svalbard y Jan Mayen","SJ"),
  ("Swazilandia","SZ"),
  ("Tayikistán","TJ"),
  ("Tailandia","TH"),
  ("Taiwán","TW"),
  ("Tanzania","TZ"),
  ("Territorio Británico del Océano Índico","IO"),
  ("Territorios Australes y Antárticas Franceses","TF"),
  ("Timor Oriental","TL"),
  ("Togo","TG"),
  ("Tokelau","TK"),
  ("Tonga","TO"),
  ("Trinidad y Tobago","TT"),
  ("Tunez","TN"),
  ("Turkmenistán","TM"),
  ("Turquía","TR"),
  ("Tuvalu","TV"),
  ("Ucrania","UA"),
  ("Uganda","UG"),
  ("Uruguay","UY"),
  ("Uzbekistán","UZ"),
  ("Vanuatu","VU"),
  ("Venezuela","VE"),
  ("Vietnam","VN"),
  ("Wallis y Futuna","WF"),
  ("Yemen","YE"),
  ("Yibuti","DJ"),
  ("Zambia","ZM"),
  ("Zimbabue","ZW");

INSERT INTO productos (nombre, descripcion, foto, precio, cantidad) VALUES
  ("Computadora","Macbook Air M2","https://images.macrumors.com/t/q-5kInZZC0CU3HsHL3HyBIHYWKQ=/1600x0/article-new/2022/06/M2-MacBook-Air-2022-Feature0012.jpg",30000,5),
  ("Celular","Motorola G9","https://s1.eestatic.com/2020/11/05/elandroidelibre/el_androide_libre_533709502_180297806_1200x675.jpg",6000,10),
  ("Cámara Web","Logitech C920","https://m.media-amazon.com/images/S/aplus-media/vc/614bdd15-3677-4df6-be81-28a046f10d55._CR0,0,1464,600_PT0_SX1464__.jpg",1500,19),
  ("Micrófono","Blue Yeti","https://www.coimprit.com.mx/wp-content/uploads/2021/11/988-000100-04.jpg",2500,19),
  ("Audífonos","Audífonos Bose","https://m.media-amazon.com/images/I/41jSuUHT8eL._AC_.jpg",6500,10);


INSERT INTO clientes (nombre, apellidos, telefono, email, direccion, cp, ciudad, pais) VALUES
  ("Jonathan","Miranda","5512345678","jonmircha@gmail.com","Calle 19 Número 20","03100","CDMX",141),
  ("Irma","Campos","5587654321","irma@gmail.com","Calle 20 Número 19","03200","CDMX",141),
  ("Daniel","Aguilar","5511223344","daniel@gmail.com","Calle 9 Número 3","03300","CDMX",141),
  ("Cecilia","Cortés","5500998877","ceci@gmail.com","Calle 1 Número 10","03400","CDMX",141),
  ("Nora","Espino","5523324114","nora@gmail.com","Calle 5 Número 3","03500","CDMX",141);

/* Este sentencia SQL mpárcara error por que el telefono que pretende insertar ya ha sido usado y el campo telefono y email, se han definido como campos únicos, por ello no se pueden duplicar */
INSERT INTO clientes (nombre, apellidos, telefono, email, direccion, cp, ciudad, pais) VALUES
  ("Ulises","Ruiz","5512345678","ulises.ruiz@gmail.com","Calle 19 Número 20","03100","CDMX",141);

INSERT INTO ventas (cliente_id, fecha, monto) VALUES
  (1,"2022-10-15",30000),
  (3,"2022-10-15",12500),
  (2,"2022-10-16",8000),
  (5,"2022-10-17",6000),
  (4,"2022-10-18",42500);

INSERT INTO articulos_x_ventas (venta_id, producto_id, cantidad) VALUES
  (1,1,1),
  (2,2,1),
  (2,5,1),
  (3,3,2),
  (3,4,2),
  (4,2,1),
  (5,1,1),
  (5,2,1),
  (5,5,1);

/* Esta sentencia SQL marcará error por que no existe el id 6 ni en la tabla ventas, ni en la de productos, ten cuidado al llenar los registros de tu BD */
INSERT INTO articulos_x_ventas (venta_id, producto_id, cantidad) VALUES
  (6,6,1);